server:
  servlet:
    context-path: /api
  port: ${SERVER_PORT:8080}

spring:
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:${user.dir}/db/app.db

auto-bangumi:
  cors:
    # 定义允许跨域请求的源（Origin）。可以设置为特定的域名、IP 地址或通配符。
    allowed-origins:
      - "*"